# Generated by Django 3.0.3 on 2020-03-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('A', 'Autorizado'), ('P', 'Pendiente'), ('N', 'Negado')], max_length=1)),
                ('documento', models.TextField()),
                ('documento_firmado', models.TextField()),
                ('fecha_autorizacion', models.DateTimeField()),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
