# Generated by Django 3.0.3 on 2020-03-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_firma', '0005_auto_20200307_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento_firmado',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='error',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
