# Generated by Django 3.0.3 on 2020-03-08 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_firma', '0006_auto_20200307_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='error',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='fecha_autorizacion',
        ),
    ]
