# Generated by Django 3.0.4 on 2020-03-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_firma', '0007_auto_20200308_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='file_pk12',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
