# Generated by Django 3.0.4 on 2020-03-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_firma', '0008_documento_file_pk12'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='file_pk12',
        ),
        migrations.AddField(
            model_name='documento',
            name='documento_tipo',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='empresa_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
