# Generated by Django 3.0.4 on 2020-03-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_firma', '0009_auto_20200314_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='clave_acceso',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
