# Generated by Django 3.0.4 on 2020-07-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_firma', '0010_documento_clave_acceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='clave_acceso',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='documento_tipo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='empresa_id',
        ),
    ]
