# Generated by Django 3.0.4 on 2020-07-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_firma', '0011_auto_20200715_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='documento_tipo',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
