# Generated by Django 3.0.4 on 2020-07-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_firma', '0013_documento_clave_acceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='clave_acceso',
        ),
    ]
