# Generated by Django 3.0.4 on 2020-07-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_firma', '0014_remove_documento_clave_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='autorizacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
