# Generated by Django 3.0.4 on 2020-07-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_firma', '0015_documento_autorizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='clave_acceso',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
